require 'settings'
require 'keymaps'
require 'themes'

require 'plugins.packer'
require 'plugins.lsp-config'
require 'plugins.bufferline'
require 'plugins.hop'
require 'plugins.nvimtree'
require 'plugins.null-ls'
require 'plugins.trouble'
require 'plugins.neogit' 
