export ZSH="/home/tufe/.oh-my-zsh"

# Theme
ZSH_THEME="spaceship"

# Aliases
alias zshconfig="lvim ~/.zshrc"
alias tmuxconfig="lvim ~/.tmux.conf"
alias reload=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
export EDITOR='vim'
 else
export EDITOR='lvim'
 fi

# update automatically without asking
zstyle ':omz:update' mode auto 

# Load plugins
plugins=(git zsh-vi-mode tmux docker docker-compose zsh-autosuggestions zsh-completions fast-syntax-highlighting sudo)

# vi-mode
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true

# TMUX
ZSH_TMUX_AUTOSTART=true                         
ZVM_VI_INSERT_ESCAPE_BINDKEY=kj

# ZSH
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
bindkey '\t' autosuggest-accept

# Random
unsetopt PROMPT_SP



# Theme and interface
LS_COLORS=$LS_COLORS:'ow=01;34:' ; export LS_COLORS
SPACESHIP_PROMPT_ORDER=(
user          # Username section
dir           # Current directory section
host          # Hostname section
git           # Git section (git_branch + git_status)
hg            # Mercurial section (hg_branch  + hg_status)
exec_time     # Execution time
line_sep      # Line break
vi_mode       # Vi-mode indicator
jobs          # Background jobs indicator
exit_code     # Exit code section
char          # Prompt character
)

# Shows System user name before directory name
SPACESHIP_USER_SHOW="always" 
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SUFFIX=" "

### NVM
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

source $ZSH/oh-my-zsh.sh 
