require 'settings'
require 'keymaps'
require 'themes'

require 'plugins.feline' 
require 'plugins.bufferline'
require 'plugins.cmp'
require 'plugins.lsp-config'
require 'plugins.lspkind'
require 'plugins.nvimtree'
require 'plugins.packer'
require 'plugins.telescope' 
require 'plugins.toggleterm' 
require 'plugins.autopairs' 
require 'plugins.autotag' 
