require 'settings'
require 'keymaps'
require 'themes'

require 'plugins.packer'
require 'plugins.cmp-config'
require 'plugins.lsp-config'
require 'plugins.bufferline'
require 'plugins.hop'
require 'plugins.tree'
require 'plugins.null-ls'
require 'plugins.project'
require 'plugins.trouble'
require 'plugins.neogit'
